apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ tpl .Values.resource.default.name . }}
  namespace: {{ tpl .Values.resource.default.namespace . }}
  labels:
    {{- include "kvm-operator.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
