apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  dockerhub-secret.yml: {{ printf "service: {registry: {dockerhubToken: %q}}" .Values.Installation.V1.Secret.Registry.Dockerhub.Token | b64enc | quote }}
