apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  dockerhub-secret.yml: |
    service:
      registry:
        dockerhubToken: {{ .Values.registry.dockerhub.token | quote }}
  proxy.yml: |
    service:
      workload:
        proxy:
          http: {{ .Values.proxy.http }}
          https: {{ .Values.proxy.https }}
