apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  dockerhub-secret.yml: |
    service:
      registry:
        dockerhubToken: {{ .Values.Installation.V1.Secret.Registry.Dockerhub.Token | quote }}
