repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, master, --branch, main, --pattern, release-*]
    - id: check-merge-conflict
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v0.8.1
  hooks:
    - id: go-test-repo-mod
- repo: git://github.com/dnephin/pre-commit-golang
  rev: ac0f6582d2484b3aa90b05d568e70f9f3c1374c7
  hooks:
    - id: go-imports
    - id: golangci-lint
    - id: go-build
    - id: go-mod-tidy
