version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "master"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: |
            k8s\.io\/*
          version_requirement: ">=0.17.0"
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "legacy-1-15"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: |
            k8s\.io\/*
          version_requirement: ">=0.17.0"
