apiVersion: v1
kind: ConfigMap
metadata:
  name: kvm-operator-configmap
  namespace: giantswarm
data:
  config.yml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: 'https://api.g8s.fra-1.giantswarm.io'
        inCluster: true
