apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kvm-operator
  namespace: giantswarm
  labels:
    app: kvm-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kvm-operator
    spec:
      containers:
      - name: kvm-operator
        image: registry.giantswarm.io/giantswarm/kvm-operator:%%DOCKER_TAG%%
        args:
        - "controller"
        - "--api-server=https://api.g8s.fra-1.giantswarm.io"
        - "--listen-address=0.0.0.0:8000"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
      imagePullSecrets:
      - name: circleci-giantswarm-registry
